version: '3'

services:
  app:
    build: ./
    image: lit/shop-app:latest
    restart: always
    ports:
      - 5000:5000
    environment:
      - LANG=C.UTF-8
      - FLASK_APP=app/run.py
        #- FLASK_ENV=production
      - FLASK_ENV=development
    volumes:
      - ./logs:/logs
      - ./:/app
    networks:
      - web_nw
    command:
      # bash -c "gunicorn --log-config configs/gunicorn-logging.ini -k gevent -w 4 -b 0.0.0.0:5000 app.run:app"
      bash -c "flask run -h 0.0.0.0"

networks:
  web_nw:
    driver: bridge
