"""empty message

Revision ID: 146b746000ce
Revises: e48d9b02df57
Create Date: 2020-04-16 15:19:51.713484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146b746000ce'
down_revision = 'e48d9b02df57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('good_state', sa.Enum('ReviewFaild', 'UnderReview', 'Reviewed'), nullable=True))
    op.add_column('goods', sa.Column('is_promote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'is_promote')
    op.drop_column('goods', 'good_state')
    # ### end Alembic commands ###
