"""empty message

Revision ID: 264363d0577c
Revises: f691e3252ec5
Create Date: 2020-04-12 15:48:21.038484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264363d0577c'
down_revision = 'f691e3252ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(length=32), nullable=False),
    sa.Column('attribute_sel', sa.Enum('only', 'many', name='sel'), nullable=False),
    sa.Column('attribute_write', sa.Enum('manual', 'list'), nullable=False),
    sa.Column('attr_values', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_attr_values'), 'attributes', ['attr_values'], unique=False)
    op.create_index(op.f('ix_attributes_attribute_name'), 'attributes', ['attribute_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attributes_attribute_name'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_attr_values'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
