"""empty message

Revision ID: 3a941b9456c3
Revises: 875d861e91b3
Create Date: 2020-03-31 16:05:57.921660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a941b9456c3'
down_revision = '875d861e91b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_ibfk_2', 'association', type_='foreignkey')
    op.drop_constraint('association_ibfk_1', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'association', 'menus', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key('association_ibfk_1', 'association', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('association_ibfk_2', 'association', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
