"""empty message

Revision ID: 400d51820ea2
Revises: 9d65032efd22
Create Date: 2020-03-28 15:57:02.666658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400d51820ea2'
down_revision = '9d65032efd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_desc', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'role_desc')
    # ### end Alembic commands ###
