"""empty message

Revision ID: 45d4d3b0058b
Revises: 3143a12f186c
Create Date: 2020-03-24 11:28:48.392951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d4d3b0058b'
down_revision = '3143a12f186c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'status')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
