"""empty message

Revision ID: 4b713bab619c
Revises: a8ef3c5b1cf0
Create Date: 2020-04-12 21:33:19.787586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b713bab619c'
down_revision = 'a8ef3c5b1cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('attribute_values', sa.String(length=200), nullable=True))
    op.add_column('attributes', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('attributes', sa.Column('updated_at', sa.Date(), nullable=True))
    op.create_index(op.f('ix_attributes_attribute_name'), 'attributes', ['attribute_name'], unique=False)
    op.create_index(op.f('ix_attributes_attribute_values'), 'attributes', ['attribute_values'], unique=False)
    op.drop_column('attributes', 'attr_values')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('attr_values', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.drop_index(op.f('ix_attributes_attribute_values'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_attribute_name'), table_name='attributes')
    op.drop_column('attributes', 'updated_at')
    op.drop_column('attributes', 'created_at')
    op.drop_column('attributes', 'attribute_values')
    # ### end Alembic commands ###
