"""empty message

Revision ID: 679cdecfe946
Revises: bbfb9ce2db33
Create Date: 2020-03-22 21:33:46.130714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '679cdecfe946'
down_revision = 'bbfb9ce2db33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submenus_created_at', table_name='submenus')
    op.drop_index('ix_submenus_updated_at', table_name='submenus')
    op.drop_column('submenus', 'created_at')
    op.drop_column('submenus', 'updated_at')
    op.drop_column('submenus', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('submenus', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('submenus', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_index('ix_submenus_updated_at', 'submenus', ['updated_at'], unique=False)
    op.create_index('ix_submenus_created_at', 'submenus', ['created_at'], unique=False)
    # ### end Alembic commands ###
