"""empty message

Revision ID: 73a07fa086b1
Revises: 146b746000ce
Create Date: 2020-04-17 09:08:48.006088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a07fa086b1'
down_revision = '146b746000ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=200), nullable=False),
    sa.Column('trad_no', sa.String(length=200), nullable=True),
    sa.Column('invoice_titile', sa.String(length=500), nullable=True),
    sa.Column('invoice_company', sa.String(length=500), nullable=True),
    sa.Column('invoice_content', sa.String(length=500), nullable=True),
    sa.Column('consignee_address', sa.String(length=500), nullable=True),
    sa.Column('order_price', sa.Float(), nullable=False),
    sa.Column('pay_status', sa.Enum('未支付', '已支付', '已取消'), nullable=True),
    sa.Column('is_send', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_table('association_order',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_order')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
