"""empty message

Revision ID: 793ea5ac3149
Revises: 679cdecfe946
Create Date: 2020-03-22 21:53:28.062391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '793ea5ac3149'
down_revision = '679cdecfe946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submenus', 'child_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submenus', 'child_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
