"""empty message

Revision ID: 801f4dca9f1a
Revises: c5722c470e44
Create Date: 2020-03-22 22:07:57.421164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '801f4dca9f1a'
down_revision = 'c5722c470e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenus', 'child_id_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('child_id_1', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
