"""empty message

Revision ID: 81df3137b2fd
Revises: 801f4dca9f1a
Create Date: 2020-03-22 22:22:31.751517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81df3137b2fd'
down_revision = '801f4dca9f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('submenus', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('submenus', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_submenus_created_at'), 'submenus', ['created_at'], unique=False)
    op.create_index(op.f('ix_submenus_updated_at'), 'submenus', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submenus_updated_at'), table_name='submenus')
    op.drop_index(op.f('ix_submenus_created_at'), table_name='submenus')
    op.drop_column('submenus', 'updated_at')
    op.drop_column('submenus', 'id')
    op.drop_column('submenus', 'created_at')
    # ### end Alembic commands ###
