"""empty message

Revision ID: 875d861e91b3
Revises: f28d4a38a9d5
Create Date: 2020-03-31 15:27:38.500316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875d861e91b3'
down_revision = 'f28d4a38a9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('association_ibfk_2', 'association', type_='foreignkey')
    op.drop_constraint('association_ibfk_1', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'association', 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key('association_ibfk_1', 'association', 'menus', ['menu_id'], ['id'])
    op.create_foreign_key('association_ibfk_2', 'association', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
