"""empty message

Revision ID: 94a0a113a438
Revises: 45d4d3b0058b
Create Date: 2020-03-25 20:17:18.796806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a0a113a438'
down_revision = '45d4d3b0058b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('menus', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_menus_created_at'), 'menus', ['created_at'], unique=False)
    op.create_index(op.f('ix_menus_updated_at'), 'menus', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_updated_at'), table_name='menus')
    op.drop_index(op.f('ix_menus_created_at'), table_name='menus')
    op.drop_column('menus', 'updated_at')
    op.drop_column('menus', 'created_at')
    # ### end Alembic commands ###
