"""empty message

Revision ID: bbfb9ce2db33
Revises: 496925366246
Create Date: 2020-03-22 15:32:38.499045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfb9ce2db33'
down_revision = '496925366246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('auth_name', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_auth_name'), 'menus', ['auth_name'], unique=False)
    op.create_table('submenus',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'parent_id', 'id')
    )
    op.create_index(op.f('ix_submenus_created_at'), 'submenus', ['created_at'], unique=False)
    op.create_index(op.f('ix_submenus_updated_at'), 'submenus', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submenus_updated_at'), table_name='submenus')
    op.drop_index(op.f('ix_submenus_created_at'), table_name='submenus')
    op.drop_table('submenus')
    op.drop_index(op.f('ix_menus_auth_name'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
