"""empty message

Revision ID: c5722c470e44
Revises: 793ea5ac3149
Create Date: 2020-03-22 22:01:24.511081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5722c470e44'
down_revision = '793ea5ac3149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('child_id_1', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'submenus', 'menus', ['child_id_1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='foreignkey')
    op.drop_column('submenus', 'child_id_1')
    # ### end Alembic commands ###
