"""empty message

Revision ID: f0d49442698c
Revises: 3e2aba961298
Create Date: 2020-03-28 14:23:30.828493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d49442698c'
down_revision = '3e2aba961298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('menus', sa.Column('updated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'updated_at')
    op.drop_column('menus', 'created_at')
    # ### end Alembic commands ###
