"""empty message

Revision ID: f328d4460ed2
Revises: 81df3137b2fd
Create Date: 2020-03-23 10:15:40.090809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f328d4460ed2'
down_revision = '81df3137b2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('level', sa.Integer(), nullable=True))
    op.alter_column('submenus', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('ix_submenus_created_at', table_name='submenus')
    op.drop_index('ix_submenus_updated_at', table_name='submenus')
    op.drop_constraint('submenus_ibfk_1', 'submenus', type_='foreignkey')
    op.drop_column('submenus', 'created_at')
    op.drop_column('submenus', 'updated_at')
    op.drop_column('submenus', 'child_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('child_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('submenus', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('submenus', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key('submenus_ibfk_1', 'submenus', 'menus', ['child_id'], ['id'])
    op.create_index('ix_submenus_updated_at', 'submenus', ['updated_at'], unique=False)
    op.create_index('ix_submenus_created_at', 'submenus', ['created_at'], unique=False)
    op.alter_column('submenus', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('menus', 'level')
    # ### end Alembic commands ###
