"""empty message

Revision ID: f691e3252ec5
Revises: 5114021ec796
Create Date: 2020-04-11 20:00:04.672126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f691e3252ec5'
down_revision = '5114021ec796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_desc', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'category_desc')
    # ### end Alembic commands ###
